### PR TITLE
Newcassel Prakruthi

### PR DESCRIPTION
**Pull request by pviswanath**
Apt,center,resident linking works
EmailId and password login validation
old and new password validation

### CODE REVIEW

**Comment by gvijayarangan** [comment]
Approved

**Comment by padmanabhanuno** [comment]
reviwed

**Review by gvijayarangan — APPROVED** [review]
Approved

**Review by padmanabhanuno — APPROVED** [review]
Merge approved

**Comment by gvijayarangan** [comment]
conflicts

**Pull request closed without merging**
